config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/tasks', to: 'tasks#index'
  get '/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get '/tasks/:id', to: 'tasks#show', as: :task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  <div class='container m-auto w-50 my-5'>
    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul class="list-group">
<% @tasks.each do |task| %>
<li class="list-group-item">
<% if task.completed %>
<input class="form-check-input me-1" type="checkbox" checked aria-label="...">
<% else %>
<input class="form-check-input me-1" type="checkbox" aria-label="...">
<% end %>
<%= link_to task.title, task_path(task) %> <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe, task_path(task),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</li>
<% end %>
<p><%= link_to "+ Add a new task", new_task_path %></p>
</ul>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_with model: @task do |f| %>
<div class="mb-3">
  <%= f.label :title, class: 'form-label' %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="mb-3">
  <%= f.label :details, class: 'form-label' %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
  <%= f.submit :submit, class: 'btn btn-primary' %>
<% end %>

<p><%= link_to '<i class="fa-solid fa-trash">Back to list</i>'.html_safe, tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<% if @task.completed %>
<p>This task is completed</p>
<% else %>
<p>This task is not completed yet</p>
<% end %>

<p><%= link_to '<i class="fa-solid fa-trash">Back to list</i>'.html_safe, tasks_path %></p>